### ISSUE TITLE
Bug: unable to upgrade application on k8s

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#116]
## Bug Description

helm upgrade --install fails with the following message:

```
Error: UPGRADE FAILED: [resource mapping not found for name: "oh-geonode-postgres-operator" namespace: "open-hypervision-dev" from "": no matches for kind "OperatorConfiguration" in version "acid.zalan.do/v1"
ensure CRDs are installed first, resource mapping not found for name: "oh-geonode-postgresql" namespace: "" from "": no matches for kind "postgresql" in version "acid.zalan.do/v1"
ensure CRDs are installed first]
```

## Reproduction Steps

Version 1.0.5

Provider: Azure AKS
Kubernetes Version: v1.25.11

values.yaml:

```
geonode-k8s:
  global:
    storageClassName: azurefile
  geonode:
    accesscontrol:
      lockdown: "True"
    general:
      externalDomain: geonode.oh.egis-group.dev
      externalScheme: https
    image:
      name: registry-gitdoit.egis.fr/go3e-eau/open-hypervision/oh-geonode
      tag: "v0.0.4-django"
    ingress:
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 600m
        nginx.org/client-max-body-size: 600m
        nginx.org/proxy-connect-timeout: 3600s
        nginx.org/proxy-read-timeout: 3600s
        nginx.org/proxy-send-timeout: 3600s
      tlsSecret: "secret-geonode"
    # à remplacer par un secret quand ok
 #   secret:
      # existingSecretName: 
  #geoserver:
    # à remplacer par un secret quand ok
   # secret:
      # existingSecretName: 
  nginx:
    external_cors:
      # -- Add Access-Control-Allow-Origin directive to allow integration from an external domain
      enabled: true
      # -- Target domain for CORS
      domain: "https://myworld.egis.com"

```

##  Behavior

A description of what you expected to happen and what actually happened.

## Additional Information

Any additional information or context that may be helpful in resolving the bug.
