### ISSUE TITLE
Bug: support of existing secret for external postgres is not complete

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#128]
## Bug Description

When you want to use an existing secret to provide user/passwords for databases hosted outside the chart, it does not work: the definition of postgres.external_postgres.secret.existingSecretName only blocks the generation of the internal secrets but the deployments don't reference the defined secret.

Moreover since there is 1 secret name for all the user/passwords, the current usage is not compatible, since we have 1 secret for each couple, with the same values.

## Reproduction Steps

```
  postgres:
    external_postgres:
      enabled: true
      secret:
        existingSecretName: "toto"
```

##  Behavior

The chart should reference the existing secret when defined and should use different names for each user/password couples.

## Additional Information

Any additional information or context that may be helpful in resolving the bug.
